### ISSUE TITLE
Add LICENSE File

### ISSUE THREAD

**Issue by UntrimmedParasail** [hyx0329/VoLTE-Patch-for-Pixel4#1]
Difficult for people to fork or use comfortably sure that they are in clear without a license. 

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by hyx0329** [comment]
The binaries(for VoLTE) in this repo don't have an explicit license, and the scripts from Magisk(`update-binary`, aka [module_installer.sh](https://github.com/topjohnwu/Magisk/blob/master/scripts/module_installer.sh) is licensed under GPL3. If you think it's valid to obtain a license through me, it should be GPL3, automatically, since I distribute the scripts in the package. However due to the fact that the binaries are never licensed explicitly(maybe in the original OS's end user agreement), I cannot assign a valid license. And yes, it might violates the ToS of github.

The only thing I can and might need to license is the `customize.sh`(maybe also the idea to fix the permission). If you are eager to obtain a license, I can release the code to public domain. But that still doesn't fix the issue.

I think there's no restriction in using the materials for personal/educational/any other fair use purposes. Forking does not need a license, as stated in [github's ToS](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#5-license-grant-to-other-users).

I hope my response addresses your concern.

**Comment by UntrimmedParasail** [comment]
> The binaries(for VoLTE) in this repo don't have an explicit license, and the scripts from Magisk(`update-binary`, aka [module_installer.sh](https://github.com/topjohnwu/Magisk/blob/master/scripts/module_installer.sh) is licensed under GPL3. If you think it's valid to obtain a license through me, it should be GPL3, automatically, since I distribute the scripts in the package. However due to the fact that the binaries are never licensed explicitly(maybe in the original OS's end user agreement), I cannot assign a valid license. And yes, it might violates the ToS of github.
> 
> The only thing I can and might need to license is the `customize.sh`(maybe also the idea to fix the permission). If you are eager to obtain a license, I can release the code to public domain. But that still doesn't fix the issue.
> 
> I think there's no restriction in using the materials for personal/educational/any other fair use purposes. Forking does not need a license, as stated in [github's ToS](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#5-license-grant-to-other-users).
> 
> I hope my response addresses your concern.

it does. i think if u put the part about module_installer.sh being gplv3 in the readme it would help, cause i dont think i saw any license headers in the file itself

**Comment by VickeyCodes** [comment]
is this still working
i want to patch my mobile phone
i forget my password 
that is why i have to reset my google pixel 4xl
so patch is finish

**Comment by hyx0329** [comment]
Hi @VickeyCodes 

> is this still working

Maybe, try it, not for carriers other than CMCC/CU/CT. For others, you need to add corresponding mbn files and modifiy mbn_sw.txt accordingly. Details are not covered here.

This module has nothing to do with your password or etc.. It replaces files and purges related cache, that's all.

Next time please open a new issue instead of sending off-topic messages :)
